### ISSUE TITLE
Parallel Coordinates: some fixes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-prototypes#114]
##### Fix
- bad legend (different fonts that the rest of the widget, label elided too much, perhaps also make it like a legend in other widgets or set in under the plot)
- extend Color attribute field to be longer (having it this short doesn't make much sense considering the full control area of the widget)
- Report not working properly (dimensions not stated with proper feature names, plot is missing)

<img width="1169" alt="parallel-coordinates-bugs" src="https://user-images.githubusercontent.com/12524972/34713924-00a02e84-f528-11e7-928b-24cc8ee5efbe.png">

<img width="1150" alt="screen shot 2018-01-09 at 10 25 28" src="https://user-images.githubusercontent.com/12524972/34713934-06fbab28-f528-11e7-8621-9a0ba8ad8194.png">

To consider:
- Do we need to display class attribute as a possible dimension? Does it make sense?

**Comment by ajdapretnar** [comment]
More fixes:
- When data gets disconnected from Parallel Coordinates, it errors with AttributeError: NoneType not in domain.
- I also got a ValueError: 'petal length' is not in domain, but for now I don't know how to reproduce it.

**Comment by ajdapretnar** [comment]
Parallel Coordinates has been deprecated. If anyone feels like taking over this task, feel free to reopen the issue.

**Comment by rawiz-coder** [comment]
It would be really cool if this was added back in, is there no demand? It's a highly useful visualisation for modes that lead to things.
