### ISSUE TITLE
On 32bit windows7 PC , there is Widget which does not appear.

### ISSUE THREAD

**Issue by anzenmusaigai** [biolab/orange3-prototypes#120]
On 32bit windows7 PC , there is Widget which does not appear.
I can see Webcam, Face Detector Icons.
OpenCV package version is 3.3.1.

There is something to worry about.
In command prompt, type "orange-canvas", there are some warning messages about PyQt4.
I have installed PyQt 5.6.0. Is this wrong?
And Orange3 version is 3.4.1. in 32bit PC.
(Warning messages)
C:\Users****\orange3-prototypes\orangecontrib\prototypes\widgets\owclock.p
y:3: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
C:\Users****\orange3-prototypes\orangecontrib\prototypes\widgets\owclock.p
y:3: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for Py
Qt4.QtCore
from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
C:\Users****\orange3-prototypes\orangecontrib\prototypes\widgets\owclock.p
y:4: RuntimeWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQ
t4.QtGui
from PyQt4.QtGui import QApplication, QCalendarWidget, QBrush, 
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orang
e3-prototypes.readthedocs.io/en/latest/')'

On windows7 64bit PC, there is following warning.
OpenCV 3.3.0
PyQt 5.6.0
Orange3 3.9.0
(Warning messages)
C:\Users****\Anaconda3\lib\site-packages\gensim\utils.py:860: UserWarning:
detected Windows; aliasing chunkize to chunkize_serial
warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users****\orange3-prototypes\orangecontrib\prototypes\widgets\owclock.p
y:3: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
C:\Users****\orange3-prototypes\orangecontrib\prototypes\widgets\owclock.p
y:3: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for Py
Qt4.QtCore
from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
C:\Users****\orange3-prototypes\orangecontrib\prototypes\widgets\owclock.p
y:4: RuntimeWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQ
t4.QtGui
from PyQt4.QtGui import QApplication, QCalendarWidget, QBrush, 
[nltk_data] Downloading package wordnet to
[nltk_data] C:\Users****\AppData\Roaming\Orange\nltk_data...
[nltk_data] Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data] C:\Users****\AppData\Roaming\Orange\nltk_data...
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
[nltk_data] Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data] C:\Users****\AppData\Roaming\Orange\nltk_data...
[nltk_data] Package punkt is already up-to-date!
[nltk_data] Downloading package opinion_lexicon to
[nltk_data] C:\Users****\AppData\Roaming\Orange\nltk_data...
[nltk_data] Package opinion_lexicon is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data] C:\Users****\AppData\Roaming\Orange\nltk_data...
[nltk_data] Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data] C:\Users****\AppData\Roaming\Orange\nltk_data...
[nltk_data] Package averaged_perceptron_tagger is already up-to-
[nltk_data] date!
[nltk_data] Downloading package maxent_treebank_pos_tagger to
[nltk_data] C:\Users****\AppData\Roaming\Orange\nltk_data...
[nltk_data] Package maxent_treebank_pos_tagger is already up-to-
[nltk_data] date!
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orang
e3-prototypes.readthedocs.io/en/latest/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://spark
.com/my-widget/docs/')'

**Comment by astaric** [comment]
PyQt4 import warnings should not be problematic. What they tell you is that some widgets (OWClock) try to use PyQt4, but it is not installed. In such cases AnyQt library does some magic to make the widgets work. If you want you can submit a pull request that fixed this, what is needed is to replace `from PyQt4 import XXX` with `from AnyQt import XXX` in offending modules.

It would also be a good idea to update your Orange installation. My guess is you are using orange from anaconda, which is quite old. You can get a newer version from conda-forge channel by following [instructions on orange webpage](https://orange.biolab.si/download/#anaconda).

**Comment by ajdapretnar** [comment]
@anzenmusaigai Can you confirm the issue is solved with newer version?

**Comment by ajdapretnar** [comment]
Considering this solved. If the new version doesn't solve this, please reopen.
