### ISSUE TITLE
Update documentation url

### ISSUE THREAD

**Issue by astaric** [biolab/orange3-prototypes#121]
An error is shown during widget discovery:

```
An error occurred while fetching help inventory
'PyQt5.QtCore.QUrl('http://orange3-prototypes.readthedocs.io/en/latest/')'
```

As a result, help files for prototype widgets are not shown (unless help files are built locally).

**Comment by ajdapretnar** [comment]
I have build the files in RTD. The error disappeared for me. Please confirm.

**Comment by astaric** [comment]
Thanks, it works now
