### ISSUE TITLE
face detection and webam widgets doesnt appear

### ISSUE THREAD

**Issue by faaeq** [biolab/orange3-prototypes#123]
##### Prototypes version
Prototypes Version: 0.9.0

##### Orange version

Orange Version: 3.9.1

##### Actual behavior
I have installed prototypes add-on on orange, but face detection and webcam doenst appear in the widgets.
i have installed opencv_python-3.4.0-cp36-cp36m-win_amd64.whl through pip since i couldnt find opencv_python‑3.2.0‑cp36‑cp36m‑win_amd64.whl on the list of opncv in the provided link.
I even installed opencv library through "conda install -c conda-forge opencv"

##### Additional info (worksheets, data, screenshots, ...)
![capture](https://user-images.githubusercontent.com/4920463/36100385-b3d2d81a-1023-11e8-895b-d8688a8d7f24.PNG)
![capture1](https://user-images.githubusercontent.com/4920463/36100386-b40eacb4-1023-11e8-9ac1-d1fdd50bdbbe.PNG)
![capture3](https://user-images.githubusercontent.com/4920463/36100388-b448f810-1023-11e8-995e-148426b7633b.PNG)
![capture4](https://user-images.githubusercontent.com/4920463/36100392-b6390ffc-1023-11e8-9633-7984e6f03abe.PNG)

**Comment by ajdapretnar** [comment]
You likely installed opencv in the wrong environment. Orange creates a separate virtual environment from which it runs.
You can drag and drop the wheel into add-ons dialogue list and install it from there.

**Comment by ajdapretnar** [comment]
Please confirm the issue is solved or still present.

**Comment by ajdapretnar** [comment]
Considered solved. Can reopen if issue persists.
