### ISSUE TITLE
Feature Statistics: send and selection in the widget

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-prototypes#125]
##### Prototypes version
0.10.0

##### Orange version

3.11.dev

##### Fix

1.) Remove 'Send Automatically' button and row selection from the widget.

OR

2.) Add a sensible output to the widget.

Currently, there's no point in having the button and row selection, since the widget doesn't output anything.

**Comment by ajdapretnar** [comment]
@pavlin-policar

**Comment by pavlin-policar** [comment]
I had deliberated this when I was working on this, and thought about option 2) you mention. You could select multiple columns and get a table on the output with only those variables. This makes the most sense imo.

My only concern is that this then becomes "Select columns" with slightly less functionality. I am not sure that duplicating functionality is really the greatest of ideas...

I do think this is still the best option, and will add it asap.

**Comment by ajdapretnar** [comment]
I agree regarding the Select Columns issue. It could potentially lead to complicated maintenance as well.
I don't mind if FeatStat is a visualization widget only. I like it as such.
