### ISSUE TITLE
Line Plot does not display anything if there is no class or discrete meta variable

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-prototypes#128]
##### Prototypes version
0.10.0

##### Orange version
3.10

##### Expected behavior
Line plot should show data also when there is no attribute that would be used in Group by.

##### Actual behavior
There is no graph drawn if the data has no categorical feature to be used in Group by.

##### Steps to reproduce the behavior
In File open iris.tab, then remove the class from the data (Select Column) and use this data for Line Plot.

**Comment by ajdapretnar** [comment]
Closed via #130.
