### ISSUE TITLE
"Feature  Statistics" wiget does not show in "Prototypes" group

### ISSUE THREAD

**Issue by Pearapon** [biolab/orange3-prototypes#146]
I use Windows 8 (64 bits) and installed "orange data mining version 3.13".
I had already got "Prototypes Wiget group" in Orange. But there is no "Feature Statistics" show in the list as shown in picture below.

Could you please help ? @pavlin-policar
Thank you very much.
Pearapon S.
Bangkok, Thailand
![orange](https://user-images.githubusercontent.com/27675996/40573179-3456048a-60e7-11e8-96af-aae8970903e2.PNG)

**Comment by pavlin-policar** [comment]
Thanks for reporting this issue. Could you please paste the output of running the "Orange Debug" executable found in "C:\Users\<your_username>\AppData\Local\Orange" so we can get a better sense of where things go wrong?

**Comment by Pearapon** [comment]
Here is the output from running "Orange Debug" from my notebook 

Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at 0x00
00003D71A9EC18>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Loading widget registry cache ('C:\\Users\\Joe\\AppData\\Roaming\\Orange\\3.13.0
\\Cache\\canvas\\registry-cache.pck').
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\data\\contexthandlers
.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owscatterp
lotgraph.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owtreeview
er2d.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\pythagoras
treeviewer.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\contexthand
lers.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\utils.py'.
D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owclock.py:3: Runti
meWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owclock.py:3: Runti
meWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore

  from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owclock.py:4: Runti
meWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQt4.QtGui
  from PyQt4.QtGui import QApplication, QCalendarWidget, QBrush, \
Error while importing 'orangecontrib.prototypes.widgets.owclock'. The widget wil
l not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owclock.py"
, line 12, in <module>
    from orangecontrib.timeseries import Timeseries
ModuleNotFoundError: No module named 'orangecontrib.timeseries'
Error while importing 'orangecontrib.prototypes.widgets.owface'. The widget will
 not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owface.py",
 line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Error while importing 'orangecontrib.prototypes.widgets.owfeaturestatistics'. Th
e widget will not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owfeaturest
atistics.py", line 31, in <module>
    from orangecontrib.prototypes.widgets.utils.histogram import Histogram
ModuleNotFoundError: No module named 'orangecontrib.prototypes.widgets.utils.his
togram'
Error while importing 'orangecontrib.prototypes.widgets.owparallelcoordinates'.
The widget will not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owparallelc
oordinates.py", line 15, in <module>
    from orangecontrib.prototypes.widgets.utils.plotly_widget import Plotly
ModuleNotFoundError: No module named 'orangecontrib.prototypes.widgets.utils.plo
tly_widget'
Error while importing 'orangecontrib.prototypes.widgets.owwebcamcapture'. The wi
dget will not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owwebcamcap
ture.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Ignoring 'D:\\Orange\\lib\\site-packages\\orangecontrib\\network\\widgets\\graph
view.py'.
libpng warning: iCCP: known incorrect sRGB profile
Saving widget registry cache with 125 entries ('C:\\Users\\Joe\\AppData\\Roaming
\\Orange\\3.13.0\\Cache\\canvas\\registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at 0x000000
3D71AF9DC8> on 'CanvasScene(objectName='', ...)'.
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3-Associate 1.1.5
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3-ImageAnalytics 0.2.0
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3 3.13.0
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3-Educational 0.1.7
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3-Prototypes 0.10.2

**Comment by Pearapon** [comment]
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at 0x00
00003D71A9EC18>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Loading widget registry cache ('C:\\Users\\Joe\\AppData\\Roaming\\Orange\\3.13.0
\\Cache\\canvas\\registry-cache.pck').
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\data\\contexthandlers
.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owscatterp
lotgraph.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owtreeview
er2d.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\pythagoras
treeviewer.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\contexthand
lers.py'.
Ignoring 'D:\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\utils.py'.
D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owclock.py:3: Runti
meWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owclock.py:3: Runti
meWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore

  from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owclock.py:4: Runti
meWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQt4.QtGui
  from PyQt4.QtGui import QApplication, QCalendarWidget, QBrush, \
Error while importing 'orangecontrib.prototypes.widgets.owclock'. The widget wil
l not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owclock.py"
, line 12, in <module>
    from orangecontrib.timeseries import Timeseries
ModuleNotFoundError: No module named 'orangecontrib.timeseries'
Error while importing 'orangecontrib.prototypes.widgets.owface'. The widget will
 not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owface.py",
 line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Error while importing 'orangecontrib.prototypes.widgets.owfeaturestatistics'. Th
e widget will not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owfeaturest
atistics.py", line 31, in <module>
    from orangecontrib.prototypes.widgets.utils.histogram import Histogram
ModuleNotFoundError: No module named 'orangecontrib.prototypes.widgets.utils.his
togram'
Error while importing 'orangecontrib.prototypes.widgets.owparallelcoordinates'.
The widget will not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owparallelc
oordinates.py", line 15, in <module>
    from orangecontrib.prototypes.widgets.utils.plotly_widget import Plotly
ModuleNotFoundError: No module named 'orangecontrib.prototypes.widgets.utils.plo
tly_widget'
Error while importing 'orangecontrib.prototypes.widgets.owwebcamcapture'. The wi
dget will not be shown.
Traceback (most recent call last):
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 2
61, in iter_widget_descriptions
    module = asmodule(name)
  File "D:\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 4
91, in asmodule
    return __import__(module, fromlist=[""])
  File "D:\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owwebcamcap
ture.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Ignoring 'D:\\Orange\\lib\\site-packages\\orangecontrib\\network\\widgets\\graph
view.py'.
libpng warning: iCCP: known incorrect sRGB profile
Saving widget registry cache with 125 entries ('C:\\Users\\Joe\\AppData\\Roaming
\\Orange\\3.13.0\\Cache\\canvas\\registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at 0x000000
3D71AF9DC8> on 'CanvasScene(objectName='', ...)'.
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3-Associate 1.1.5
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3-ImageAnalytics 0.2.0
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3 3.13.0
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3-Educational 0.1.7
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Ora
nge3-Prototypes 0.10.2

**Comment by markotoplak** [comment]
I confirm this bug on a Mac that has the add-on was installed through the Add-ons dialog in a bundle.

The problem is that some files are not included in the add-on installation package. Fix coming soon!

**Comment by Pearapon** [comment]
HOw can I get this fix for "Feature Statistics" ?
