### ISSUE TITLE
Explain prediction: score and error value not displayed

### ISSUE THREAD

**Issue by guikool** [biolab/orange3-prototypes#164]
##### Prototypes version
0.11

##### Orange version

3.16

##### Expected behavior
Hello,

I'm trying to use the module "Explain prediction" to compute the most interesting loadings from a RF model. 
After few minutes, only the column "Value" is filled, "score" and "Error" are filled with "0.000" values.

It could be really cool to solve this, since model interpretations are really lacking in other orange module.
Thanks,

Best,
G

**Comment by AndrejaKovacic** [comment]
Please install the development version, since we have a new version of this widget already. New release is a few weeks away.
If the problem persists, attach some screenshots. Is your data by any chance very sparse?

**Comment by guikool** [comment]
Thanks for your reply
My data come from a metabolomic study, missing value and uv scaling have been applied as  preprocess steps before RF model. This last is really good (0.98 AUC). The raw data are not especially sparsed.
I'm a newby in Orange, please tell me the procedure to install the dev version.
Thanks
G.

**Comment by AndrejaKovacic** [comment]
It is explained in the project's [ReadMe](https://github.com/biolab/orange3-prototypes/blob/master/README.md), try the first two code snippets.
Just to check, so after a few minutes, the widget has completed all of the calculations?

**Comment by guikool** [comment]
Ok, done using pip install e  .
same issue as before...even after complete computation
If you want to have a try, I've shared with you the dataset.
[Stat-univ-orange-v3.xlsx](https://github.com/biolab/orange3-prototypes/files/2453912/Stat-univ-orange-v3.xlsx)
Continuous variable are in column and class individual in the first column. These data come from a LCMS metabolomic approach using plants.
I've done a RF model which seem pretty good.
![image](https://user-images.githubusercontent.com/22800372/46581898-e0ea4500-ca3f-11e8-9847-f8f3478b4fce.png)

Thanks again for your help
Best
G.

**Comment by ajdapretnar** [comment]
@guikool I get normal values using a very simple pipeline with just RF and Explain Predictions. The computation however, takes for ever. I can see the results 'interactively' if I open the window, they get updated occasionally, but I am still at 0% even after a couple of minutes. Strange.

I would assume your preprocessing could be the issue. Since you are using spectrometry data, I suggest you use our Spectroscopy add-on, which offers specific preprocessors, such as Savitzky-Golay.  https://github.com/Quasars/orange-spectroscopy

**Comment by guikool** [comment]
You're right, it's really slow but it works without preprocessing..The results are pretty good.
We use to scale data in metabolomics to avoid effect of variable amplitude range. Still I don't understand why it impairs prediction calculation.
Thanks for your Help
Best,
G.

**Comment by ajdapretnar** [comment]
@AndrejaKovacic could you please have a look at this and close, if the issue is resolved? Thanks!
