### ISSUE TITLE
IPython Connector Widget not passing stored data

### ISSUE THREAD

**Issue by tdierickx** [biolab/orange3-prototypes#186]
##### Prototypes version
0.12

##### Orange version
3.22.0

##### Expected behavior
IPython Connector Widget to pass data on to other widgets

##### Actual behavior
I can see variables stored in Jupyter session in the dropdown, but when I hook the widget up to Data Table widget it's blank and when I hook up to Python Script widget all input variables are blank. I even "reset signal" and connected IPython connector widgets' "Raw Object" output to Python Script widget's "Object" input and still all input variables are blank.

##### Steps to reproduce the behavior
1) From Jupyter notebook: 
`x = [10, 20, 30]`
`%store x`

2) From Orange, connect IPyton widget to Python Script widget
3) reset signals
4) Connect "Raw Object" to "Object"
5)  Attempt to access in_objects but is empty

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/16019221/63220895-2befe100-c156-11e9-98a5-4cd7f80b552e.png)

**Comment by tdierickx** [comment]
update: by (1) storing another variable in Jupyter and (2) changing the IPython Connector dropdown to different variable, it appears to have forced an update of the downstream signals and the data appeared! 

It seems the widget does *not* work when there's only _one_ stored Jupyter object to pick from. I was able to confirm this by adding and removing stored variables in Jupyter and the widget on the orange side works as long as there's more than one to pick from the dropdown changes to a different item. If there's only one to pick from then it does not work.

**Comment by ajdapretnar** [comment]
Original IPython connector has been deprecated. A new IPython Script has been reimplemented in #194.
