### ISSUE TITLE
Unique: settings should be domain-dependent

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-prototypes#188]
Unique crashes when fed new data with a new domain. Clear the settings when new domain is incoming.

**Comment by DLWheeler** [comment]
This widget was extremely useful the one time I was able to use it--it worked like a charm!  But it can only be used once since it remembers the first domain it sees permanently.  Is there any way at all to reset it?

**Comment by janezd** [comment]
@ajdapretnar, @DLWheeler, please see whether #195 fixes this.

The widget was ancient and also in "prototypes" for a reason.

**Comment by DLWheeler** [comment]
Yes, it works beautifully!  Thank you very much for fixing this ancient but very useful widget.
