### ISSUE TITLE
LDA Widget is not working

### ISSUE THREAD

**Issue by jureyherrera** [biolab/orange3-prototypes#191]
##### Prototypes version
0.12.0

##### Orange version

3.24.1
##### Actual behavior

LDA widget is not working, in the past we found this tool pretty useful, for instance to perform analyses like PC-LDA.

##### Steps to reproduce the behavior
We can reproduce the error, for instance using the Iris data set where there is a pretty clear target variable.

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/31166917/73254728-41fed480-41bf-11ea-80b5-e4a4ccb61305.png)

##### Message Error
![image](https://user-images.githubusercontent.com/31166917/73254813-66f34780-41bf-11ea-97d1-d59cdf8f9eac.png)

**Comment by janezd** [comment]
This widget was a prototype and today we decided to start a new one, so the current version is being removed.

**Comment by jureyherrera** [comment]
Thanks a lot for your reply, looking forward to see the new version.
