### ISSUE TITLE
Explain prediction widget

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-prototypes#197]
This widget would explain individual predictions. The graph is similar to [force_plot form SHAP](https://github.com/slundberg/shap).

Here are two suggested designs. The first one skips attributes names for less important features (on that user can use a tooltip), while the second list all variables. We decided to show the 
10 most important features on the graph.

![explain-predictions-v1](https://user-images.githubusercontent.com/6421558/78597870-8c9b6d80-784e-11ea-9165-6ec87c07191e.png)

![explain-predictions-v2](https://user-images.githubusercontent.com/6421558/78597881-8efdc780-784e-11ea-99ef-dc1fc65d27a5.png)

Model output is predicted value (probability for a target class or prediction itself in case of regression).

The Y-axis is not always between 0 and 1 - it must be computed based on the SHAP values.

On the stripe, SHAP values are shown. On the right of each segment attribute name and its value is shown.

Zoom regulate the size of the chart along Y-axis (if chart too high pane is scrollable)

**Control area**
- **target class** - the class for which we make an explanation (active only for classification)

**Inputs**
- Model
- Background data
- Data (to explain - for an explanation we take the first-row instance)

**Outputs**
- Shap values for explained row instance (table with one row)

**Comment by ajdapretnar** [comment]
Explain Predictions already exists. Please check it. @AndrejaKovacic

**Comment by AndrejaKovacic** [comment]
Current widget calculates approximations, as calculating shapely values exactly is np hard i believe. This library seems to do it somewhat differently and is optimized for tree ensemble methods. I'll make a pull request for explain predictions today (with some minor wrinkles), so we can think about whether it is fast enough or if we should include shap library.

**Comment by PrimozGodec** [comment]
Thank you Andrea. I tested your widget but it is still slower than SHAP. As much I understand SHAP makes few improvements - a combination of more methods - that it is much faster also on other models. This issue still needs to be discussed and will probably wait here a bit.

**Comment by AndrejaKovacic** [comment]
My reservation was with adding dependency for what is perhaps only a speed up with specific models.
I didn't see the explain model widget proposal earlier. If that one is implemented, then I am for using SHAP for explain predictions widgets - added dependency would already be there, so why not speed up explain predictions as well.
