### ISSUE TITLE
Unique: available attributes not updating

### ISSUE THREAD

**Issue by AndrejaKovacic** [biolab/orange3-prototypes#202]
##### Orange version

3.25.0

##### Expected behavior
Available attributes match the domain of input table.

##### Actual behavior
Sometimes some attributes are not available or are listed as available even though they are not in the domain.

##### Steps to reproduce the behavior
Load iris dataset, connect it to unique. Change iris to zoo. Available attributes stay the same.

**Comment by ajdapretnar** [comment]
Fixed via #195.
