### ISSUE TITLE
Create table widget: possible improvements

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-prototypes#214]
I have merged the widget to the master of Prototypes to sit here for a while and get tested. After while it will be moved to educational. Here we can comment about possible improvements. My suggestions are:

- Currently, widget removes data when the input data is disconnected and when the same table is reconnected the table is still empty. My idea is to remember data via Context setting and refill the table when the same table is on the input.
- Currently, the user is not allowed to create a table with numbers and words in same column. I would allow that. If only numbers are in the column the variable would be Continuous else it would be discrete.

**Comment by ajdapretnar** [comment]
I would also start with widget with 3x3 or 5x5 default table. 1x1 really doesn't make sense.
When moving around the table with a tab, the fields get cleared. I think they shouldn't. They also get cleared on enter. Strange behavior. I would expect to press enter to exit the modify mode and for arrow keys to work.
Dates don't get recognized as a TimeVariable.
