### ISSUE TITLE
New chat GPT widget use

### ISSUE THREAD

**Issue by pepeto** [biolab/orange3-prototypes#260]
##### Orange version
 3.35

##### Expected behavior
unknown

Please, could you give an example of use of chat GPT new widget?
Is there any way to create a column with the answers?
Thank you!!!

**Comment by VesnaT** [comment]
A new widget ChatGPT Constructor (#262) may solve that.

**Comment by roolio** [comment]
that's really really cool, thanks! 
I was about to write myself such an extension, when I stumbled upon your code. 
a blog post on this extension could contribute to Orange success :) 

Kudos

**Comment by roolio** [comment]
small digression on the chatGPT Constructor : I managed to get it output some json structure, e.g. with a question giving 3 answers, the 3 answers being in a json array, e.g. : {"qualities": ["intelligence", "adaptability", "loyalty"]}.  

now I'd like to access the different text elements in json with extensions like Textable or Text Mining (for a word cloud, or whatever) . Any idea on how to do that? (if not possible, I could probably store the json output in a postgres table, convert it into real json, and access it back with a SQL Table, but it kinda "breaks" the workflow)

**Comment by ajdapretnar** [comment]
You can ask ChatGPT to give you a simple list of qualities (no json), just a list, separated by comma. Then pass it to Text to Columns, which will create a column per quality. Word cloud would also work with a simple list.
