### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by Ethan72** [biolab/orange3-prototypes#67]
How do I install this so that I can use the widgets in this package in Orange?

**Comment by markotoplak** [comment]
https://www.youtube.com/watch?v=OANsA6fMJKg

**Comment by ajdapretnar** [comment]
This, however, won't install the OpenCV library you will need for facial recognition.
You can:
```
git clone https://github.com/biolab/orange3-prototypes.git
cd orange3-prototypes
pip install -e .
conda install -c menpo opencv3=3.2.0 # (or opencv=2.4.11, I'm not sure which)
```

But please know that this is a prototype add-on and it is not fully supported by our developers.

**Comment by Ethan72** [comment]
Thank you. I have been trying to figure out how to install this package for over a week and finally got it to work now! The only think is that when it is about to finish it says Error: Package missing in current osx-64 channels. Does this mean that I can not install this package if I am using Mac OS?

**Comment by ajdapretnar** [comment]
Yes, I'm just researching this issue. The conflict is likely with Python 3.6. It looks like the library wasn't yet built for this version of Python. I'm currently experimenting with Windows, where it works with [Gohlke's](http://www.lfd.uci.edu/~gohlke/pythonlibs/) packages.
You could try with [pip](https://pypi.python.org/pypi/opencv-python) for OSX.
`pip install opencv-python`

**Comment by Ethan72** [comment]
The pip3 install opencv-python command worked for installing that last bit. Now I have all of those lines of code have been successfully executed and run in my Terminal on my Mac OS. Now that all of those have successfully installed, how do I get the widgets, like webcam capture, face detector, etc to appear in Orange when I launch it?

**Comment by ajdapretnar** [comment]
They should be automatically registered upon installing Orange3-Prototypes.

**Comment by Ethan72** [comment]
For me, for some reason I am still having trouble viewing the webcam capture and face detector widgets when I launch my Orange software installed on my Mac (3.3). I have successfully run all of those lines of code though... using pip3 install instead though b/c as a default Mac uses python 2.7 in its Terminal.

**Comment by Ethan72** [comment]
![success 3](https://cloud.githubusercontent.com/assets/26082571/23675237/9656c64c-032d-11e7-80c4-ba9a4daf46ad.jpeg)

**Comment by kernc** [comment]
So if you finally run:
```bash
python3 -m Orange.canvas -l 4
```
are there no widgets in the Prototypes category? Is there any output in the terminal that would indicate errors and can you share it?

**Comment by Ethan72** [comment]
Ok, so never mind about that. I tried installing the opencv python again and it worked this time. The webcam capture widget as well as the face detector one are now appearing. However, I think there might be an issue, because whenever I double click the webcam capture widget it opens fine, but then when I go to close it, it quits out and Orange crashes. Maybe this is just a Mac problem, and plus this package is not actively maintained. At least I got the widgets to appear though.

**Comment by nikicc** [comment]
> You could try with pip for OSX.
> pip install opencv-python

The problem @Ethan72 had with this was is that if you install Orange from a bundle, then open a terminal and run the command the system's pip is used instead of the one from the bundle. Consequently the dependency is installed in the wrong environment. What you probably want on OSX is something like:

```
/Applications/Orange3.app/Contents/MacOS/pip install opencv-python
```

**Comment by kernc** [comment]
> but then when I go to close it, it quits out and Orange crashes. 

@Ethan72 Please submit the terminal output of the command `python3 -m Orange.canvas -l 4` (i.e. verbose, log-level-4 logged output) when observing that behavior as a new issue. Thanks.

**Comment by Ethan72** [comment]
![error 4](https://cloud.githubusercontent.com/assets/26082571/23722664/1a9441c8-03fb-11e7-92e1-cc39a7780efc.jpeg)
 Does this help? Still not sure why Orange is crashing when I exit out of the webcam capture widget.

**Comment by kernc** [comment]
`-l` is minus lowercase L. `python3 -m Orange.canvas -l 4`. Please run again, and preferably, copy the output text and attach it as a txt file.

The ImportError above is due to `python3` (and  `pip3`) being from _/Library/Frameworks/..._), not the same python (pip) that came bundled with Orange app, which contained PyQt, whereas your "`pip3` environment" doesn't. Perhaps also run `pip3 install pyqt5` before rerunning Orange.

**Comment by Ethan72** [comment]
[Terminal Run.txt](https://github.com/biolab/orange3-prototypes/files/828958/Terminal.Run.txt)
 I am so sorry I read that completely wrong. I attacked the output from running that line of code. Maybe this will help.

**Comment by nikicc** [comment]
I can also reproduce the same behaviour. In my case it segfaults.

**Comment by ajdapretnar** [comment]
+1

**Comment by Ethan72** [comment]
Hmm, glad its not just me who is having this issue. Is there any way to correct/fix the segfault error then?
