### ISSUE TITLE
Remove obsolete widgets

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-prototypes#77]
Clean up Prototypes add-on.
Remove:
- Last File Capture (doesn't work)
- ModelMap Projection Rank (is implemented as Rank Projections elsewhere)
- CreateClass (is now in core Orange)

**Comment by jerneju** [comment]
If https://github.com/biolab/orange3/pull/2445 is approved and merged, we will might want to consider removing two other widgets as well:

- Linear Projection
- FreeViz

**Comment by PrimozGodec** [comment]
FreeViz was updated recently so I guess we leave it in prototypes?

**Comment by ajdapretnar** [comment]
The idea is to avoid duplicate widgets (causes problems when browsing by widget name) and to keep Prototypes clean. I don't want it to be a widget junkyard. 😆  As for FreeViz, we can perhaps remove it once it is properly merged in core?

**Comment by PrimozGodec** [comment]
So I will leave it in prototypes for now. All other widgets from the list will be removed.

**Comment by jerneju** [comment]
@ajdapretnar : FreeViz is already merged in core. Linear Projection is not.

**Comment by ajdapretnar** [comment]
You are right, how did I miss this!? This requires a blog asap (well, after the release, obviously).
As for LinProj, I have it in core. You probably mean the updates to LinProj?

**Comment by jerneju** [comment]
Yes, updates.

**Comment by ajdapretnar** [comment]
Data Sets is also redundant.

**Comment by ajdapretnar** [comment]
Then for LinProj I think it depends where you are pushing the changes? If you need it in Prototypes for testing the changes, it should stay here. If you are pushing directly to core, then I vote for removing it.

**Comment by jerneju** [comment]
I am pushing changes directly to Core. As far as I'm concerned both FreeViz and Linear Projection can be removed from Prototypes.
